services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jadpai-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - .next:/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:6969
      - DOCKER_API_URL=http://jadpai-app:6969

networks:
  jadpai-network:
    external: true

volumes:
  node_modules: